### PR TITLE
[Important] allow sending data ONLY notifications for FCM notifications

### PR DESCRIPTION
**Pull request by SebastienMelki**
Hey @appleboy ran into a little issue here need this tweak to be able send and process background notifications on android

If you want to process android notifications in the BACKGROUND, they need to be data notifications, as in not contain the "notification" key in the payload.

This little change achieves it, because omitempty on structs for the json encoding does not work on sub-structs except if it is a pointer to it and set to nil.

### CODE REVIEW

**Comment by appleboy** [comment]
@SebastienMelki https://cloud.drone.io/appleboy/gorush/195/1/7

Please update the code format. Try `make fmt` command.

**Comment by SebastienMelki** [comment]
> code format error.

on it thanks

**Comment by SebastienMelki** [comment]
> make fmt

done

**Comment by appleboy** [comment]
@SebastienMelki Thanks.

**Pull request merged**
