### PR TITLE
add makefile build commands for darwin OS

### PR DESCRIPTION
**Pull request by keremoge**
add makefile build commands for **darwin** OS for macOS local builds. 

Example usage on MacOS:
`make build_darwin_amd64`

### CODE REVIEW

**Comment by slimus** [comment]
Hi @keremoge! I'm not sure, but we have `make release` to build all targets and arches. I think we have to delete all `build_linux_*` make commands.

@appleboy am I right?

**Comment by keremoge** [comment]
> Hi @keremoge! I'm not sure, but we have `make release` to build all targets and arches. I think we have to delete all `build_linux_*` make commands.
> 
> @appleboy am I right?

Hi, but `make release` only builds for **amd64**
https://github.com/appleboy/gorush/blob/9d47494585d5b58fc838c3f78b792c54c1707e26/Makefile#L10

**Comment by slimus** [comment]
@appleboy please, help us. Should we create new commands or add a new arch to old commands? What do you think?

**Comment by appleboy** [comment]
We can create a new command for the developer and also need to find a new tool to release multiple versions like https://goreleaser.com/

**Pull request merged**
