### PR TITLE
Set default value for ios.max_concurrent_pushes

### LINKED ISSUE #536: Not working IOS push notifications when failed push
When sending a push notification to IOS, the request hangs and there is no response, it does not write logs and does not help in sync: true. In v1.11.2 release it is OK!

### PR DESCRIPTION
**Pull request by raoulh**
I upgraded gorush running on my server and the old config did not have `ios.max_concurrent_pushes`. The default value was then 0 and the iOS queue was blocked forever.

This PR simply set a sane default value for `MaxConcurrentPushes` to not be 0.

Fixes #536

### CODE REVIEW

**Comment by slimus** [comment]
Hi @raoulh! Thank you for your PR.
I think we don't need it, because if you update the app, you need update config, and add new params (or delete old, or update).

**Comment by raoulh** [comment]
I think that it does not hurt to have this included. And it's also done for other config options like `conf.Core.QueueNum` which is set to a default value if it's 0.

Sure you need to update your config when you update your app. But I lost a lot of time to dig why it was not working anymore:
 - Because nothing was written anywhere in the logging console when gorush is started
 - Nothing is written in the Readme that this parameter is new from this version
 - I'm not the only one who had this issue and lost of time after updating #536 

From all this points I think it would be nice with all future users to have those better "update path" with default sane value to prevent people losing their time because it's not working anymore...

So yes, you can ignore and reject this PR, but it's not being nice with users of this project

**Comment by slimus** [comment]
@raoulh, thank you for your explanation. Sorry if my comment looks negative. I tried to understand. Also, I'm just a contributor here :) 

I think about 2 options here:
1. Merge your config (all params) with the default values.
2. Validate params and show errors if needed.


You made the first option, but only for one param. Maybe we should write a merger for all params now? Or maybe we should validate all params now. 

@appleboy what do you think?

@raoulh sorry again about my comment.

**Comment by appleboy** [comment]
@slimus I agree with @raoulh points. I will add the default value for `max_concurrent_pushes` parameter.

**Comment by appleboy** [comment]
@raoulh @slimus I will make a new PR to fix the issue asap.

**Comment by raoulh** [comment]
@appleboy Why a new PR, is mine not good enough?

**Pull request closed without merging**
