### PR TITLE
Expand environment variables in yaml

### PR DESCRIPTION
**Pull request by pazams**
We meet again @appleboy 😄  Thanks for writing this server!

This PR adds the capability to expand environment variables in the YAML config
e.g
```yaml
core:
  port: "${GORUSH_PORT}"
```
This is similar to how docker-compose [allows it](https://docs.docker.com/compose/compose-file/#variable-substitution) 
This should also address the request at #180

### CODE REVIEW

**Comment by appleboy** [comment]
@pazams How about this package https://github.com/jinzhu/configor ? I found this package in your GitHub repository list so we can define the global variable by the following config and set prefix name as `GORUSH_`.

```go
type SectionAutoTLS struct {
	Enabled bool   `yaml:"enabled" env:"ENABLED"`
	Folder  string `yaml:"folder"  env:"FOLDER"`
	Host    string `yaml:"host"    env:"HOST"`
}
```

**Comment by pazams** [comment]
Thanks for commenting @appleboy !
I indeed started to add the env feature with `configor` package, but eventually trashed it.
Here's my analysis:

## "configor"

### Pros:
- Popular proven package.

### Cons:
- Code coupling: We only wanted to add env support, but now all of the yaml parsing is coupled with that package.
- Lack of explicitness: What happens when both env variable is present and yaml config value?
e.g this line from the package readme.
```
// Set prefix by config
configor.New(&configor.Config{ENVPrefix: "WEB"}).Load(&Config, "config.json")
```
- Reproducibility: Different environments could use different code paths (yaml or env), which may cause confusion.

## Expanding env variables in yaml config (with "envexpand")

### Pros:
- Does only one thing: If at some point you are not pleased with the performance of "envexpand", you can easily exchange it for a different small package that will expand env variables.

- Explicit: A value is either always given or always taken from env variable. Reading the yaml file is all that is needed to understand which case is it for each field. 

- Style: Follows the style of the popular docker-compose format of expanding variables.

### Cons:
- The expansions works on the complete yaml file. This means it could also expand also the field names rather than the values. However, since `$`,`{`,`}` are not valid golang identifiers, we are safe. The other option is to use reflection to deep traverse all the fields and then expand only the values. That would be more "clean" solution, but seems unnecessary in my opinion.

**Comment by appleboy** [comment]
@pazams Thanks for your feedback. One condition We need to discuss. If someone set the default value `port: 3001` and how to update the port number using `Expanding env variables`.

```yml
port: 3000
```

I want to change the default value in yaml file as the following command.

```
PORT=3001 gorush -c config.yml
```

**Comment by appleboy** [comment]
maybe we should consider another solution [viper](https://github.com/spf13/viper).

**Comment by pazams** [comment]
> I want to change the default value in yaml file as the following command.

We can't. If we could, then the config file is no longer the source of truth. The only way would be:
```
  port: "${GORUSH_PORT}"
  port_default: 3000
```
and have the switch conditioned programatically, but that's not really a good solution.

IMO, `gorush`, as an open source package, should come with all the defaults hardcoded into the config file, and then users can choose which one they'd like to control via env variables.

> maybe we should consider another solution viper.

`viper` is an awesome project! my opinions on integrating it in this context, are the same as  integrating with `configor`.

**Comment by appleboy** [comment]
I will try to integrate `viper` in this project.

**Comment by pazams** [comment]
Thanks 👍

**Comment by appleboy** [comment]
@pazams gorush support environment configuration now.

```
$ docker run -e GORUSH_CORE_PORT=8089 appleboy/gorush
time="2017/10/23 - 04:30:28" level=debug msg="Init App Status Engine as memory"
time="2017/10/23 - 04:30:28" level=debug msg="worker number is 2, queue number is 8192"
time="2017/10/23 - 04:30:28" level=debug msg="gRPC server is disabled."
time="2017/10/23 - 04:30:28" level=debug msg="HTTPD server is running on 8089 port."
```

Please pull the latest tag from docker hub. See the implementation #293

**Pull request closed without merging**
