### PR TITLE
fix: use mutable content and content available when set.

### PR DESCRIPTION
**Pull request by hchienjo**
This PR uses the content available and mutable content fields when set. In the older version e.g 1.4.0 and in the legacy FCM API the content available was set [here](https://github.com/appleboy/gorush/blob/1.4.0/gorush/notification.go#L56) and used here in the [request](https://github.com/appleboy/gorush/blob/1.4.0/gorush/notification.go#L346). It would be good for when these fields are set they can be propagated to Firebase Cloud Messaging under the [APNS Config section](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#ApnsConfig). 

The 2 fields influence how Apple Push Notification system handles the notifications on the end user device.

Content available is for background notifications hence the notification shouldn't have an alert or sound according to this [reference](https://developer.apple.com/documentation/usernotifications/generating-a-remote-notification).

### CODE REVIEW

**Comment by hchienjo** [comment]
@appleboy another on related to IOS push notifications on Firebase.

**Comment by appleboy** [comment]
I will take it.

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
@hchienjo Thanks

**Comment by hchienjo** [comment]
Thanks! Is there a plan to tag a new version?

**Pull request merged**
