### PR TITLE
Check status of response before retry send push

### LINKED ISSUE #420: Limitation of sending messages with max_retry for unregistered tokens
If we set `max_retry` to more than 0 in the configuration file, sending messages will be repeated. For the case when the device token is not registered, this is not relevant.

### PR DESCRIPTION
**Pull request by slimus**
Check response before retry send pushes
fix #420

### CODE REVIEW

**Comment by slimus** [comment]
@appleboy is it possible to add me to `appveyor` account?

**Comment by appleboy** [comment]
Appveyor can't grant permission for multiple accounts in the project setting but I grant the `Run build` and `View` permission for Guest.

Screen Shot 2020-04-30 at 4 10 19 PM

**Comment by appleboy** [comment]
@slimus Can you revert the change in Windows build? We can create another PR to fix the issue.

**Comment by slimus** [comment]
I will create new PR

**Pull request closed without merging**
