### PR TITLE
Added mutable_content option for Firebase

### PR DESCRIPTION
**Pull request by edpelesh**
It is now possible to send `mutable_content` option to Firebase which gets forwarded as `mutable-content` option for APNS.

A link to official documentation is: https://firebase.google.com/docs/cloud-messaging/http-server-ref#mutable_content

### CODE REVIEW

**Comment by appleboy** [comment]
@edpelesh dependency PR merged. Please update the vendor.

**Comment by edpelesh** [comment]
@appleboy some checks fail because of wrong or outdated Firebase API Key: `FCM server send message error: 401 error: 401 Unauthorized`.

I also wanted to ask if this update is going to be released at https://hub.docker.com/r/appleboy/gorush/?
Impressed with the tooling available for this project, good job! 👍

**Comment by appleboy** [comment]
@edpelesh It will be released at hub.docker.com/r/appleboy/gorush automatically after merged into the master branch and build successfully.

**Comment by appleboy** [comment]
I will fix the `missing key problem`

**Comment by appleboy** [comment]
try the latest tag https://hub.docker.com/r/appleboy/gorush/tags/

**Comment by edpelesh** [comment]
It works. Thanks for such a fast response!

**Pull request merged**
