### PR TITLE
Separate storage logic from actual business logic

### PR DESCRIPTION
**Pull request by Luoxin**
The storage part should only perform basic add, delete, change and check of data, rather than embed business. If you need to add business-related data stores later, in principle, you only need to change the code of 'status', rather than change the interface and difference of' storage '

### CODE REVIEW

**Comment by appleboy** [comment]
build fail

**Comment by Luoxin** [comment]
I am trying to fix build failure.

**Comment by appleboy** [comment]
@Luoxin Thanks.

**Comment by appleboy** [comment]
https://github.com/appleboy/gorush/releases/tag/v1.16.0

**Pull request merged**
