### PR TITLE
Webpush support

### PR DESCRIPTION
**Pull request by jrx-jsj**
This pull request includes Webpush support #248. Previous PR including additional changes has been closed.

### CODE REVIEW

**Comment by jrx-jsj** [comment]
@appleboy I think the PR is now in a good shape. Tests include some valid webpush subscription that may be added through environment variables like it is done for Android.

**Comment by appleboy** [comment]
I will implement this feature using https://github.com/SherClockHolmes/webpush-go

**Comment by winwisely99** [comment]
Web Push support is needed for our open source project.

Can anyone comment one what is holding this up from being merged.

**Comment by appleboy** [comment]
outdated

**Pull request closed without merging**
